### ISSUE TITLE
Organizational changes to this repo's layout

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/ARC-specfication#119]
Upon internal discussions and following quite a lot of confusion and out-of-sync information, these repos:

- [ARC-specification](https://github.com/nfdi4plants/ARC-specification)
- [isa-ro-crate-profile](https://github.com/nfdi4plants/isa-ro-crate-profile)
- [arc-cwl-ro-crate-profile](https://github.com/nfdi4plants/arc-cwl-ro-crate-profile)
- [arc-datamap-ro-crate-profile](https://github.com/nfdi4plants/arc-datamap-ro-crate-profile)

Will undergo a re-organization of the repo layout:
- All repos will be connected to zenodo for DOI minting (this repo is already connected, the profiles are currently not)
- A new `release` branch will be introduced, of which `HEAD` will always point to the respectively latest release tag. This means that the content of the `release` branch will always be in sync with the latest release, the content of the zenodo record, and the respective DOI
- The `release` branch will be the default branch on GitHub
- A new `dev` branch will be created, which is where **ALL** PRs other than releases must be targeted to. 
- The `release` branch will be protected from direct pushes, and only accept PRs from the `dev` branch
- A small contribution guide will be added to all repos readmes

**Comment by muehlhaus** [comment]
Yes, this is an excellent strategy.

**Comment by kMutagene** [comment]
Done, although the HEAD of `release` will point to to the latest tag after the next release. I have done it this way so that contribution rules are visible on the default branch from now on.
