### ISSUE TITLE
Inconsistency in ARC specification re workflows?

### ISSUE THREAD

**Issue by UrsulaE** [nfdi4plants/ARC-specfication#125]
Only a small issue, if it is one, but it might lead to unnecessary confusion in the ARC validation, assuming both sentences refer to the same run description file:

Under caption "High-Level Schema" it reads "[Each top-level runs subdirectory (?)] MUST be accompanied by a per-run CWL workflow description, stored in `<run_name>.cwl` as further described [below](#run-description)." 

In the "below", it reads "Each such subdirectory MUST contain a workflow description `run.cwl`, given..."

**Comment by kMutagene** [comment]
cc @caroott @HLWeil

**Comment by HLWeil** [comment]
Hey @UrsulaE, thanks for the issue. Will fix this, to be consistent with the other files, i.e. `run.cwl` without the name of the run.

**Comment by HLWeil** [comment]
fixed in 1635955f5668882ede7832ba82a2deebff9f557f and will be part of next release

**Comment by UrsulaE** [comment]
Thanks, Ursula
