### ISSUE TITLE
Practical guide

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/ARC-specfication#32]
From the introduction:

> This specification is intended as a practical guide.
 
For me, the file specification is no practical guide in the sense that it explains things (why and how should I do it). I read it as technical documentation. So I´m not sure if it should be called "practical guide". Some motivation might also be helpful to convince researchers to use ARCs.

**Comment by muehlhaus** [comment]
This sentence should indicate that by providing explanations for software authors as "NOTES", we go a bit beyond a classical specification.
