### ISSUE TITLE
History of ARC specification

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/ARC-specfication#36]
In the extension section, the ARC development is mentioned. A link leading to the ARC specification history would be helpful. There has already been put a lot of effort into ARCs. This could be highlighted by providing a history with the milestones and major improvements between versions. Additionally, this shows development geared by and towards the users.

[Of course I know that we are talking about V1.0 ... there is not much history yet.]

**Comment by cgarth** [comment]
The extensions section was condensed into a statement that [semantic versioning](https://semver.org/spec/v2.0.0.html) will be used; future version of the spec should most definitely contain history/change information.
