### ISSUE TITLE
Clarification of strict separation of data and metadata

### ISSUE THREAD

**Issue by johanneswerner** [nfdi4plants/ARC-specfication#37]
In the section ARC Structure and Content

> ARCs are based on a strict separation of data and metadata content (...)

This separation is unclear. From the section High-Level Schema

> Each assay is a collection of files, together with a corresponding metadata file (...)

It would be helpful to explain what is meant with strict separation or how it should look like. It seems that different folders for data and metadata are not intended with that strict separation - if it is meant on file basis, this is what most researchers are doing nowadays anyway already. At least I have not worked with a researcher who combined experimental data or analysis results with metadata.

**Comment by cgarth** [comment]
Reformulated to clarify.
