### ISSUE TITLE
Clarification for not capturing repository-specific metadata requirements

### ISSUE THREAD

**Issue by johanneswerner** [nfdi4plants/ARC-specfication#38]
In the section Shareable and Publishable ARCs

> The attribute publishable does not imply that data and metadata contained in an ARC are suitable for publication in a specific outlet (e.g. PRIDE, GEO, EBI) nor that metadata is complete or enables reusability of data. While it may be straightforward to convert the ARC schema into one required by specific publishers or repositories, additional metadata requirements may be enforced during conversion. These are intentionally not captured in this specification.

Why are those specifications not captured? Is it because the requirements for specific publishers or dedicated repositories are too different? If so, then I would add this information to the text (as it might be interesting for researchers to have this information covered by an ARC, at least for standard repositories, such as PRIDE or ENA). Otherwise, researchers might be reluctant to use ARCs at all, if they still need to work on their metadata submission independent from the ARC architecture.

**Comment by muehlhaus** [comment]
These requirements are moving targets depending on the user-desired end-point repository and therefore not captured in our specs. However, we support the user by providing target specific [templates](https://github.com/nfdi4plants/SWATE_templates/tree/main/templates).
