### ISSUE TITLE
Remove uncompressed large files from ARCs

### ISSUE THREAD

**Issue by johanneswerner** [nfdi4plants/ARC-specfication#39]
In the section Community Specific Data Formats, there are fastq and SAM files listed. Both should be removed as there is no reason to keep large files uncompressed (gz for fastq and SAM->BAM conversion).

**Comment by cgarth** [comment]
This is a sensible approach at the policy level. It should be kept out of the specification however to avoid regulating an exhaustive (and by default incomplete) list of file formats.
