### ISSUE TITLE
Date and time information in filenames

### ISSUE THREAD

**Issue by johanneswerner** [nfdi4plants/ARC-specfication#41]
In the section Directory and File Naming Conventions

> Date and time information might be encoded as well if it provides a better ordering or information for the particular purpose.

I advise to not add this information into filenames. There are of course scenarios where this might be useful (time series experiment), but based on my experience, this rather leads to overall very messy filenames. Thus, I suggest to remove this sentence.

**Comment by cgarth** [comment]
moved to discussion (agree)
