### ISSUE TITLE
Rephrasing suggested for section Assay Data and Metadata

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/ARC-specfication#48]
>Assay Data and Metadata
All measurement data sets are considered as assays and are considered immutable input data. Assay data MUST be placed into a unique subdirectory of the top-level assays folder. All ISA metadata specific to a single assay MUST be annotated in a in the file isa.assay.xlsx at the root of the assay's subdirectory. This workbook MUST contain a single assay that can be organized in one or many worksheets. Worksheets MUST be named uniquely within the same workbook. A worksheet named assay MUST store the STUDY ASSAYS section defined on investigation-level of the ISA model and are not required in the isa.investigation.xlsx . These include the terms Study Assay Measurement Type, Study Assay Measurement Type Term Accession Number, Study Assay Measurement Type Term Source REF, Study Assay Technology Type, Study Assay Technology Type Term Accession Number, Study Assay Technology Type Term Source REF, and Study Assay Technology Platform. Additional worksheets MUST contain a table object with fields organized on a per-row basis. The first row of the table object MUST be used for column headers. A Source MUST be indicated with the column heading Source Name. Every table object MUST define at least one source per row. A Sample MUST be indicated with the column heading Sample Name. The source sample relation MUST follow a unique path in a directed acyclic graph, but MAY be distributed across different worksheets.

To be honest, I´m totally lost reading this paragraph. Some suggestens: 
* I´d refer to the **Example ARC structure** to indicate where multiple assays would be located and to show that the structure repeats itself. 
* Also, I´d strengthen that within each assay (e.g. assay_drought) there is another isa.assay.xslx by replacing _the root of the assay's subdirectory_ with _the root of **that** assay's subdirectory_. 
* Also, the connection / link between isa.assay.xlsx and *this workbook* is unexpected. (Which workbook? Ah ... the Excel.) 
* _This workbook MUST contain a single assay that can be organized in one or many worksheets._ This sentence is unclear. Suggestion: This workbook (isa.investigation.xslx) MUST contain exclusively metadata about the assay in same subdirectory. The metadata can be organized in one more worksheets within the isa.investiagtion.xslx workbook.
* _A worksheet named assay MUST store the STUDY ASSAYS section defined on investigation-level of the ISA model and are not required in the isa.investigation.xlsx_ Sounds like a contradiction to me.
* _Every table object MUST define at least one source per row._ Is more than one source possible?
* The table is missing some explanation. Is that an example? If yes, for what?

**Comment by muehlhaus** [comment]
Workbooks, Worksheets and tables are explained in the [XLSX specification](https://www.loc.gov/preservation/digital/formats/fdd/fdd000398.shtml#:~:text=The%20XLSX%20format%20uses%20the,a%20rectangular%20grid%20of%20cells.) already linked in our spec.
