### ISSUE TITLE
Metric for quality of data and metadata

### ISSUE THREAD

**Issue by HGauza** [nfdi4plants/ARC-specfication#49]
In the section *Mechanism for Quality Control of ARCs*
> (...) the quality of data and metadata (this metric will be established in the next version) (...)

(Meta)data quality and mechanisms for quality control are important and interesting topics. Is there any estimate for that improvement to give to the community? 
Also see my discussion point on that topic. There is a working group in the SDC / BioDATEN context that also deals with that topic.

**Comment by muehlhaus** [comment]
Has been moved to the discussions.
